### ISSUE TITLE
Warnings : cannot find source files

### ISSUE THREAD

**Issue by jsrockstar132** [flauc/angular2-notifications#15]
The directive is working great! but i see these warnings - 

`WARNING in ./~/angular2-notifications/lib/notifications.service.js
Cannot find source file '../src/notifications.service.ts': Error: Cannot resolve 'file' or 'directory' ../src/notifications.service.ts in /Users/sachin/myproject/node_modules/angular2-notifications/lib`

`WARNING in ./~/angular2-notifications/lib/simpleNotifications.component.js
Cannot find source file '../src/simpleNotifications.component.ts': Error: Cannot resolve 'file' or 'directory' ../src/simpleNotifications.component.ts in /Users/sachin/myproject/node_modules/angular2-notifications/lib`

and few more similar warnings...

I am using webpack and have imported the directive like this - 
`import {SimpleNotificationsComponent,
    NotificationsService} from 'angular2-notifications/components';`

Thanks in advance!

**Comment by jsrockstar132** [comment]
Sorry, this is a duplicate issue - https://github.com/flauc/angular2-notifications/issues/6

**Comment by jsrockstar132** [comment]
I found that in map files the sources refer to a path in src folder. 

In notification.component.js.map - 

`{"version":3,"file":"notification.component.js","sourceRoot":"","sources":["../src/notification.component.ts"],"names":[],"mappings":";;;;;;;;;;AAAA,qBAA8D,eAAe,CAAC,C...`

I think the warnings are due to this.

**Comment by flauc** [comment]
Hi, sorry for the late response. 

I've actually figured out what the issue was. Webpack expects to find the source (src) files in side of the node_module, but i don't include it with the package. 

I always figured my approach was better since it keeps the package as light as possible. But this is the second time someone has pointed this out so i'll include it with the next publish.  

Thank you for the heads up :+1:
