### ISSUE TITLE
not working in chrome for android ?

### ISSUE THREAD

**Issue by lghinet** [flauc/angular2-notifications#150]
hello 
not working in chrome for android ?
are you using web workers ?

**Comment by flauc** [comment]
Hi @lghinet, 

No I'm not using web workers, any other idea what might be causing it?

**Comment by lghinet** [comment]
i think this is the only way you can show notifications on devices, as native notifications 
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification

**Comment by flauc** [comment]
Oh so you were refering to the PushNotification part of the library? Yes thous won't work on mobile.

**Comment by MennoVS** [comment]
I think we should use the ServiceWorkerRegistration.showNotification API if it's available and use the Notification API as a fallback. It seems to use the same interface as Notification so that shouldn't be a problem. I think I'll make a PR for this in the next few days.

**Comment by flauc** [comment]
That's a great idea, thanks 👍

**Comment by MennoVS** [comment]
@flauc I started on this feature, it seems to be a bit more complicated than I thought. 

1. We need to add a service worker JS file to the repo, which we can use to make a service worker instance. The issue here is that this file needs to be copied over to whichever build folder the developer uses, so using it would require extra configuration. This also causes the URL to be change, so the developer needs to provide it when calling PushNotificationService.initializeServiceWorker.

2. Since a service worker would be registered on the users browser, we need to decide when to remove it. We could do it on window.beforeunload, to leave as little clutter as possible. An alternative is to have the developer decide when to remove it, this also makes sense since it's the developer that initializes it.

If would appreciate your opinion on these issues!

**Comment by flauc** [comment]
I believe creating a service worker should be up to the user of the library. NgPush has been moved to a separate project:

https://github.com/flauc/ng-push

If you notice any issues regarding it, please open an issue on that repo.
