### ISSUE TITLE
Element implicitly has an 'any' type because type 'Icons' has no index signature.

### ISSUE THREAD

**Issue by pgrm** [flauc/angular2-notifications#213]
I'm getting the above mentioned error:

````
ERROR in C:/.../node_modules/angular2-notifications/src/simple-notifications/services/notifications.service.ts (51,72): Element implicitly has an 'any' type because type 'Icons' has no index signature.

ERROR in C:/.../node_modules/angular2-notifications/src/simple-notifications/services/notifications.service.ts (51,72): Element implicitly has an 'any' type because type 'Icons' has no index signature.
````

For some reason the angular2-notifications in the node_modules folder contains the typescript src folder and that one is being used instead of the dist folder. Any ideas how to solve it?

**Comment by Sky4CE** [comment]
Error	TS7017	Element implicitly has an 'any' type because type 'Icons' has no index signature. ...\node_modules\angular2-notifications\src\simple-notifications\services\notifications.service.ts	51

Please support noImplicitAny ts setting !

**Comment by flauc** [comment]
hmm

I do have: `"noImplicitAny": true,` in the tsconfig.json

**Comment by pgrm** [comment]
oh, I forgot to mention, this issue only started to appear with version `0.7.4` I didn't have it in `0.7.3`

**Comment by Sky4CE** [comment]
@flauc , that's odd, because ts with noImplicitAny option would never allow code like `this.icons[type]`.
As I wrote in comment in related commit you can easily fix this with `(<any>this.icons)[type]`

**Comment by Sky4CE** [comment]
@flauc , I'm sorry, but seems like you ignoring the fact that your lib is completely broken since May 17. Is it so hard to implement that little fix I pointed you several times ?? My whole application failed to build due to your bug, I have more than 100 dependencies and none of them has such problem. Sorry, but my patience runs out as I see that you releasing new versions but not fixing critical bug which prevents to use this lib. So, please, asking you again, fix this error ! 
[How to fix](https://github.com/flauc/angular2-notifications/commit/b729c83230e74d612e377a47dfd4178f79746372)

**Comment by flauc** [comment]
@Sky4CE if you have the time for it feel free to send a PR. If you don't, feel free to use another library. 
Also, I'm using the newest version in 10+ projects and it works well in every single one of them.

**Comment by Sky4CE** [comment]
@flauc I don't need another lib, your lib is awesome. Here is my [PR](https://github.com/flauc/angular2-notifications/pull/233)

**Comment by flauc** [comment]
@Sky4CE Thank you, 

I'm sorry to lash out, I just started this library some time ago and have since ended out with my hands full with other projects, making it hard for me to maintain the library. Therefore any help is greatly appreciated 👍
