### ISSUE TITLE
notifications are not shown, with no errors!

### ISSUE THREAD

**Issue by yahyaKacem** [flauc/angular2-notifications#55]
Hi, first thanks for this plugin, I tried it and no notifications are shown here's a [plunker](https://plnkr.co/edit/zwK8KrNRh2yaiVTenJ2A?p=preview) with the error, when you click on the button nothing happen !!
Am I doing something wrong here?
Is there a step missing I need to do to get it to work?
Also the `NotificationsService` should by provided in the `main.ts` file or the `app.component.ts` file, otherwise an error will occur, this step is missing from the docs.

**Comment by flauc** [comment]
Hi @yahyaKacem 

Here is the updated [plunker](https://plnkr.co/edit/iNkq2dZ1MYKmq7Bfwb2B?p=preview) with the fix.

The problem occurred because you have registered the provider for the `NotificationsService` in the child component as well as in `main.ts` so you actually had two instances of the service in your application. 

The documentation is confusing your right. I'll have it updated, thanks for the input :+1:
