### ISSUE TITLE
webpack is throwing warnings

### ISSUE THREAD

**Issue by fxck** [flauc/angular2-notifications#6]
![image](https://cloud.githubusercontent.com/assets/1303561/13940238/f996d032-efdb-11e5-8d31-763f701c3100.png)

**Comment by flauc** [comment]
I've only ever used systemjs as the module loader on my angular2 projects. But i have tested this library on a webpack starter project and didn't have any errors. This is the starter project i used [link](https://github.com/preboot/angular2-webpack). You could also have a look at this issue if it helps #5

**Comment by fxck** [comment]
I'm using the most popular one out there https://github.com/AngularClass/angular2-webpack-starter

**Comment by flauc** [comment]
Let me try and set it up.

**Comment by fxck** [comment]
It's using angular beta11, which means you'll be getting some zone errors as well, but don't mine those, it's not fault of your lib.

**Comment by flauc** [comment]
Hey. I've figured out what the problem was. Everything actually works as expected but for some reason this webpack-starter expects to find the source ts files in the angular2-notifications library. 

So if you were to clone this repository and copy the src file to the node_modules/angular2-notifications folder in the webpack-starter you wouldn't get the warnings and everything would work just as before. 

This is weird because i always thought that not including the src files in the published library is the right way to go. Because it really isn't necessary and it increases the size of the library. It's also not a problem with webpack in general just with this starter.

But like i said the library works with this webpack-starter either way.

**Comment by flauc** [comment]
Hope this helps. 

You can also clone this repository in to your project and it would work with out throwing the warnings. Only the src folder is needed if you choose this approach.

**Comment by flauc** [comment]
I think you should also consider switching to the system.js module loader. It's what the angular2 team recommends and you'll notice immediately how much less configuration is required to get started.
