### ISSUE TITLE
Source code is duplicated

### ISSUE THREAD

**Issue by mvar** [flauc/angular2-notifications#78]
I'm not an expert in TS/JS field, but why source code is duplicated in different files? From what I see, other libraries doesn't have this issue.

BTW, thanks for providing such a great library.

**Comment by flauc** [comment]
I'm not sure what you mean exactly. Where is it duplicated? 

I'm glad you like the library 👍

**Comment by mvar** [comment]
For example, `components.d.ts` contains the same code as each separate `.ts` file.

**Comment by flauc** [comment]
Oh that's what you mean. Well I've added that because for some reason webpack users couldn't map to declarations in the lib folder. 

I'm not an expert for webpack so i don't know why that is the case. 

Anyway that's not a problem for using the library because thous are just type declarations that don't compile in the build so they don't take up any extra space in your environment.

**Comment by mvar** [comment]
My point is not about extra space, but about bigger chances to make a mistake :)

**Comment by flauc** [comment]
Yes you are right about that. Sadly I'm not quit sure how to avoid it.

**Comment by flauc** [comment]
Cleared up now.
